name: kwetter
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  chopper: ^5.1.0
  crypt: ^4.2.1
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.2.5
  firebase_core: ^2.4.1
  firebase_crashlytics: ^3.0.9
  firebase_storage: ^11.0.10
  firebase_core_platform_interface: ^4.5.2
  image_picker: ^0.8.6
  permission_handler: ^10.2.0
  provider: ^6.0.4
  shared_preferences: ^2.0.15
  universal_io: ^2.0.4

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.2
  chopper_generator: ^5.1.0+1

flutter:
  uses-material-design: true
  assets:
    - assets/
