name: end-to-end test

on: [push, workflow_dispatch]
jobs:
  android:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        api-level:
          - 29
      fail-fast: true
    steps:
      - uses: actions/checkout@v3
      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Install Flutter dependencies
        run: flutter pub get
      - name: Run integration tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          arch: x86_64
          profile: Nexus 6
          script: flutter test test/app_test
